frontend/hedera_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('topics/', include("topics.urls")),
    path('user/', include("user.urls")),
    path('', login_required(TemplateView.as_view(template_name="topics/index.html")), name="index"),
]

frontend/topics/urls.py
from django.contrib import admin
from django.urls import path

from . import views


urlpatterns = [
    path("create-topic/", views.CreateTopics.as_view(), name="create_topics"),
    path("create-message/", views.CreateMessage.as_view(), name="create_message"),

    path("get-memo/<int:pk>", views.get_memo, name="get_memo"),
    
]

frontend/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="user/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

frontend/topics/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class TimeStampModel(models.Model):
    created_date = models.DateField(
        blank=True,
        db_column="CreatedDate",
        verbose_name="Create Date",
        help_text="Date on which the record was inserted.",
        editable=False,
        null=True,
    )
    updated_date = models.DateField(
        blank=True,
        editable=False,
        verbose_name="Update Date",
        help_text="Date on which the record was updated.",
        db_column="UpdatedDate",
        null=True,
    )

    class Meta:
        abstract = True


class ObjectStateModel(TimeStampModel):
    is_active = models.BooleanField(
        default=True,
        verbose_name="Is Active",
        help_text="This column is used for soft delete. Users can reactivate the entry via portal",
        db_column="IsActive",
        null=True,
    )
    is_delete = models.BooleanField(
        default=False,
        verbose_name="Is Delete",
        help_text="This column is used for hard delete. Users cannot reactivate the entry via portal",
        db_column="IsDeleted",
        null=True,
    )

    class Meta:
        abstract = True


# Create your models here.
class Topics(models.Model):
    topic_user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    topic_id = models.IntegerField(primary_key=True, blank=True,)
    shard_id = models.IntegerField(default=0, blank=True,)
    realm_id = models.IntegerField(default=0, blank=True,)
    topic_name = models.CharField(max_length=256, blank=True,)
    topic_memo = models.CharField(max_length=2560, blank=True,)

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.topic_id:
            self.create_date = timezone.now()
        self.update_date = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.realm_id}.{self.shard_id}.{self.topic_id} [{self.topic_name}]"

frontend/user/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

frontend/topics/forms.py
from django import forms

from .models import Topics


class CreateTopicForm(forms.ModelForm):
    # consensusClient = forms.
    class Meta:
        model=Topics
        fields=[
            "topic_id",
            "topic_name",
            "topic_memo",
            
        ]
    
    def save(self):
        print(self.cleaned_data)


class CreateMessageForm(forms.ModelForm):
    
    topic_id = forms.ModelChoiceField(queryset=None)
    
    def __init__(self, *args, **kwargs):
        topic = kwargs.pop("topic")        
        super().__init__(*args, **kwargs)
        self.fields["topic_id"].queryset = topic
    
    class Meta:
        model=Topics
        fields=[
    
            "shard_id",
            "realm_id",
            "topic_name",
            "topic_memo",
            
        ]
    
    def save(self):
        print(self.cleaned_data)

frontend/user/forms.py
# from django import forms

# from .models import UserProfile

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ["image"]

frontend/topics/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse

from .forms import CreateTopicForm, CreateMessageForm
from .models import Topics

class CreateTopics(View):
    template_name = "topics/create_topic.html"
    
    def get(self, request, *args, **kwargs):
        form = CreateTopicForm()
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = CreateTopicForm(request.POST)
        
        return render(request, self.template_name, locals())

class CreateMessage(View):
    template_name = "topics/create_message.html"
    
    def get(self, request, *args, **kwargs):
        topic = Topics.objects.all().values_list("topic_id", flat=True)
        print(topic)
        form = CreateMessageForm(topic=topic)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = CreateMessageForm(request.POST)
        
        return render(request, self.template_name, locals())

def get_memo(request, pk):
    if request.is_ajax:
        try:
            memo = Topics.objects.get(topic_id=pk).topic_memo
            return HttpResponse(memo)            
        except: 
            return HttpResponse(404)
    return redirect("/")

frontend/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.views import View
# from .forms import ProfileUpdateForm


# @login_required
# def profile(request):
#     """ 
#     Summary. 
  
#     This is function based view for rendering user profile page. 
#     Users can edit few details using this page. 
  
#     Parameters: 
#     request: Takes request from frontend. If request.method is POST and form is valid then saves the data to database.
  
#     Returns: 
#     page: renders an HTML page of with ProfileUpdateForm. 
  
#     """
#     if request.method == "POST":  # Check if the method to is POST
#         p_form = ProfileUpdateForm(
#             request.POST, request.FILES, instance=request.user.profile
#         )  # Send required information to Profile Update Form

#         if p_form.is_valid():
#             p_form.save()  # Save in the database
#             messages.success(request, f"Your account has been updated!")
#             return redirect("profile")
#     else:
#         p_form = ProfileUpdateForm(
#             instance=request.user.profile
#         )  # If it is not POST, then push the default or already uploaded pic for view

#     context = {"p_form": p_form}
#     return render(request, "user/profile.html", context)

frontend/topics/templates/topics/base.html
{% load static %}
{% load i18n %}

{% block extrahead %} {# Embeds Extra Resources #}
{% endblock %} {# Ends Extra Resources #}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Hedera Consensus</title>
  <!-- Tell the browser to be responsive to screen width -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'topics/asset/image/favicon.ico' %}">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/timesheet.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/hover.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/css/index.css' %}">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/css/font-awesome-animation.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/Ionicons/css/ionicons.min.css' %}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/daterangepicker.css' %}">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/bootstrap-datepicker.min.css' %}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static 'topics/asset/plugins/iCheck/all.css' %}">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/bootstrap-colorpicker.min.css' %}">
  <!-- Bootstrap time Picker -->
  <link rel="stylesheet" href="{% static 'topics/asset/plugins/timepicker/bootstrap-timepicker.min.css' %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static 'topics/asset/css/select2.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'topics/asset/dist/css/AdminLTE.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'topics/asset/dist/css/skins/_all-skins.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/css/datatables.min.css' %}">
  <link rel="stylesheet" href="{% static 'topics/asset/css/timesheet_datatable.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="skin-blue sidebar-mini fixed sidebar-mini-expand-feature" style="height: auto; min-height: 100%;">
  <div class="wrapper">
    
    

    <div class="content-wrapper" id="timesheet">
      <!-------content-wrapper---------->
      <section class="content">

        <!--Key Indicators-->

        {% block content %}{% endblock %}

      </section>
      <!-------/content---------->
    </div>
    <!-- /.tab-content -->
  </div>



  {% now "Y" as current_year %}
  {% blocktrans %}
  <footer class="main-footer">
    Copyright &copy; {{ current_year }} <a href="http://decimalpointanalytics.com/" target="_blank">Decimal Point
      Analytics Pvt Ltd.</a>
    All rights
    reserved.
    <span class="pull-right" style="color:#008080; font-size:12px;">Version 0.9.10</span>
  </footer>
  {% endblocktrans %}

  <!-- ./wrapper -->

  <!-- jQuery 3 -->
  <script src="{% static 'topics/asset/js/jquery.min.js' %}"></script>
  <script src="{% static 'topics/asset/js/current_nav_selection.js'%}"></script>
  <script src="{% static 'topics/asset/js/toggle_pending.js'%}"></script>
  <!--Script for datatables-->
  

  <script type="text/javascript">
    $(document).ready(function () {
      $('[data-toggle="popover"]').popover({
        placement: 'bottom',
        trigger: 'hover'
      });
    });
  </script>

  <!-- jQuery UI 1.11.4 -->
  <script src="{% static 'topics/asset/js/jquery-ui.min.js' %}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{% static 'topics/asset/js/bootstrap.min.js' %}"></script>
  <!-- Select2 -->
  <script src="{% static 'topics/asset/js/select2.full.min.js' %}"></script>
  <!-- InputMask -->
  <script src="{% static 'topics/asset/plugins/input-mask/jquery.inputmask.js' %}"></script>
  <script src="{% static 'topics/asset/plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
  <script src="{% static 'topics/asset/plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>
  <!-- Sparkline -->
  <script src="{% static 'topics/asset/js/jquery.sparkline.min.js' %}"></script>
  <!-- jvectormap -->
  <script src="{% static 'topics/asset/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
  <script src="{% static 'topics/asset/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
  <!-- jQuery Knob Chart -->
  <script src="{% static 'topics/asset/js/jquery.knob.min.js' %}"></script>
  <!-- date-range-picker -->
  <script src="{% static 'topics/asset/js/moment.min.js' %}"></script>
  <script src="{% static 'topics/asset/js/daterangepicker.js' %}"></script>
  <!-- bootstrap datepicker -->
  <script src="{% static 'topics/asset/js/bootstrap-datepicker.min.js' %}"></script>
  <!-- bootstrap color picker -->
  <script src="{% static 'topics/asset/js/bootstrap-colorpicker.min.js' %}"></script>
  <!-- bootstrap time picker -->
  <script src="{% static 'topics/asset/plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src="{% static 'topics/asset/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
  <!-- SlimScroll -->
  <script src="{% static 'topics/asset/js/jquery.slimscroll.min.js' %}"></script>
  <!-- iCheck 1.0.1 -->
  <script src="{% static 'topics/asset/plugins/iCheck/icheck.min.js' %}"></script>
  <!-- FastClick -->
  <script src="{% static 'topics/asset/js/fastclick.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'topics/asset/dist/js/adminlte.min.js' %}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="{% static 'topics/asset/dist/js/pages/dashboard.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'topics/asset/dist/js/demo.js' %}"></script>

  <script type="text/javascript" src="{% static 'topics/asset/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'topics/asset/js/custom.js' %}" type="text/javascript"></script>
  <!-- <script src="{% static 'topics/asset/js/require.js' %}" type="text/javascript"></script> -->
  
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
    })      
  </script>


</body>

</html>

frontend/topics/templates/topics/create_message.html
{% extends "topics/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
<script src="{% static 'topics/asset/js/hedera/bundle.js' %}"></script>
<div>
    <form id="request_form" method="POST">
        {% csrf_token %}
        <div class="newmidpoint">
            <div class="row">
                <div class="col-md-4">
                    <div class="box-body">

                        <div class="form-group">
                            <label for="exampleInputEmail1">Topic ID</label>
                            {{form.topic_id|add_class:"form-control"|append_attr:"placeholder: Topic ID" }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="newmidpointa">
            <div class="row">
                <div class="col-md-12">
                    <div style="padding: 12px;" class="form-group" style="padding-right: 50px;">
                        {{ form.topic_memo|add_class:"form-control"|append_attr:"placeholder: Enter a Memo"|attr:"rows:10 cols:15"}}
                    </div>
                </div>

                <div class="col-md-12">
                    <label for="exampleInputEmail1"></label>
                    <div style="padding: 12px;" class="form-group" style="padding-right: 50px;">
                        {{form.topic_name|add_class:"form-control "|append_attr:"placeholder: Company Name" }}
                    </div>
                </div>
            </div>
        </div>

        <hr style="margin-top: 2px;margin-bottom: 2px;">

        <div class="row" style="padding:20px 10px;">
            <div class="col-xs-12">
                <p class="note">Note</p>
                <p class="notepoint">If you have existing topic enter the topic number</p>
                <p class="notepoint">Click ON generate new topic to create a new topic</p>
                </p>
            </div>
        </div>

        <hr style="margin-top: 2px;margin-bottom: 2px;">

        <div class="row  row-centered" style="padding:20px 10px;">
            <div class="col-xs-2 col-centered">
                <center><button id="createMessage" type="submit" class="btn btn-block btn-warning">Add Message</button>
                </center>
            </div>

        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        $('#id_topic_memo').prop('disabled', true);
        $("#id_topic_id").change(function () {
            
            topic = $("#id_topic_id").val();
            $.ajax({
                cache: false,
                type: "GET",
                async: false,
                data: {},
                url: "{% url 'get_memo' 0 %}".replace(0, topic),
                success: function (data) {
                    $("#id_topic_memo").val(data)
                },
            });
        });
    });
</script>

<script>
    $(document).ready(function () {
        topic = $("#id_topic_id").val();
        $("#createMessage").click(function (e) {
            e.preventDefault();
            message = $("#id_topic_name").val();
            $.ajax({
                type: "POST",
                async: false,
                data: {
                    "topicId": topic,
                    "message": message,
                },
                url: "http://192.168.2.211:3000/consensus/create-message/",
                success: function (data) {
                    console.log(data)
                },
                error: function (err) {
                    console.log(" ")
                }
            });
        });
    })
</script>

{% endblock %}

frontend/topics/templates/topics/create_topic.html
{% extends "topics/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>

<div>
    <form id="request_form" method="POST">
        {% csrf_token %}
        <div class="newmidpoint">
            <div class="row">
                <div class="col-md-4">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Shard</label>
                            {{form.shard_id|add_class:"form-control" }}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Realm</label>
                            {{form.realm_id|add_class:"form-control" }}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-body">

                        <div class="form-group">
                            <label for="exampleInputEmail1">Topic ID</label>
                            {{form.topic_id|add_class:"form-control"|append_attr:"placeholder: Topic ID" }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="newmidpointa">
            <div class="row">
                <div class="col-md-12">
                    <div style="padding: 12px;" class="form-group" style="padding-right: 50px;">
                        {{form.topic_name|add_class:"form-control "|append_attr:"placeholder: Name" }}
                    </div>
                </div>

                <div class="col-md-12">
                    <div style="padding: 12px;" class="form-group" style="padding-right: 50px;">
                        {{ form.topic_memo|add_class:"form-control"|append_attr:"placeholder: Enter a Memo"|attr:"rows:10 cols:15"}}
                    </div>
                </div>
            </div>
        </div>


        <hr style="margin-top: 2px;margin-bottom: 2px;">

        <div class="row" style="padding:20px 10px;">
            <div class="col-xs-12">
                <p class="note">Note</p>
                <p class="notepoint">If you have existing topic enter the topic number</p>
                <p class="notepoint">Click ON generate new topic to create a new topic</p>
                </p>
            </div>
        </div>

        <hr style="margin-top: 2px;margin-bottom: 2px;">

        <div class="row  row-centered" style="padding:20px 10px;">
            <div class="col-xs-2 col-centered">
                <center><button id="generateTopic" type="submit" class="btn btn-block btn-warning">Create a New Topic
                        ID</button></center>
            </div>
            <div class="col-xs-2 col-centered">
                <center><button id="getTopic" type="submit" class="btn btn-block btn-warning">Get Topic Details</button>
                </center>
            </div>
            <div class="col-xs-2 col-centered">
                <center><button id="setTopic" type="submit" class="btn btn-block btn-warning" hidden>Get Topic
                        Details</button>
                </center>
            </div>

        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        $("#setTopic").hide();

        $("#generateTopic").click(function (e) {
            e.preventDefault();
            if ($("#id_topic_memo").val()) {
                topicId = generateTopic();
                // console.log(topicId)
                $("#setTopic").show();
            }
            else {
                alert("please enter a Memo")
            }

        });
        $("#getTopic").click(function (e) {

            e.preventDefault();
        });
        $("#setTopic").click(function (e) {
            topicId = $("#id_topic_id").val();

            setTopic(topicId)
        });
    });
</script>
<script src="{% static 'topics/asset/js/hedera/dotenv_bundle.js'%}"></script>
<script src="{% static 'topics/asset/js/hedera/client_bundle.js'%}"></script>
{% endblock %}

frontend/topics/templates/topics/index.html
{% extends "topics/base.html" %}
{% load static %}
{% block content %}

<a href="{% url 'create_topics' %}">Create a Topic</a>
<br>
<a href="{% url 'create_message' %}">Add a Message</a>

{% endblock %}

frontend/user/templates/user/login.html
{% extends "topics/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!----------Error Messages---------------->
<div>
    {% if form.errors %}
    <div class="row ">
        <div class="col-md-12">
            <div class="errormsg">
                {% for field in form %}
                {% for error in field.errors %}
                <p>
                    <center> {{ error }} </center>
                </p>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <p>
                    <center> {{ error }} </center>
                </p>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
<!----------/Error Messages---------------->
<div class="container" id="loginbox">

                <form method="post">
                    {% csrf_token %}
                    <div class="row loginform">
                        <div class="col-lg-10 col-offset-1">
                            <div class="form-group">
                                <label for="usr">Username</label>
                                {{ form.username|add_class:"form-control" }}
                            </div>
                        </div>

                        <div class="col-lg-10 col-offset-1">
                            <div class="form-group">
                                <label for="usr">Password</label>
                                {{ form.password|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-lg-12">
                            <h6 class="fg_pass"><a href="{% url 'password_reset' %}">Forgot Password?</a></h6>
                        </div>

                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-info mainbutton">Sign In</button>
                        </div>
                    </div>
                </form>
           
</div>

{% endblock %}

frontend/user/templates/user/logout.html
{% include "topics/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
Successfully Logged out
{% endblock %}

frontend/user/templates/user/password_reset.html
{% extends "topics/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="container" id="loginbox">
	<div class="row wh_bg">
		<div class="col-sm-6" style="padding:0px;" id="hero">
			<div class="mid-point-right hero-img">
				<center><img src="{% static 'user/img/logo.png' %}" class="img-responsive" width="180px">
				</center>
				<center><img src="{% static 'user/img/login_bg.png' %}" class="img-responsive login-bg vert-move"
						width="400px"></center>
				<h3></h3>
				<p></p>
			</div>
		</div>
		<div class="col-sm-6" style="padding:0px;">
			<div class="mid-point-left" data-aos="fade-left">
				<form class="form" method="POST">
					{% csrf_token %}
				<h2>Forgot Password</h2>
				<p>Confirm your email and we'll send the instructions</p>
				<div class="line"></div>
				
					<div class="row loginform">
						<div class="col-lg-10 col-offset-1">
							<div class="form-group">
								<label for="usr">Email address</label>
								{{ form.email|add_class:"form-control"|append_attr:"placeholder:Type Email Address.."}}
							</div>
						</div>

					</div>
				

				<div class="row">
					<div class="col-lg-12">
						<button type="submit" class="btn btn-info mainbutton">Get Verification Link</button>
					</div>
				</div>
				<p></p>
				<p></p>
				</form>
				<p class="text-center"><a href="{% url 'login' %}" class="fgpass">Take me back!</a></p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

frontend/user/templates/user/password_reset_complete.html
{% extends "topics/base.html" %}
{% block content %}

<div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
<div class="card card-login card-hidden">
        <div class="card-header card-header-primary text-center">
            <h4 class="card-title">Email Sent</h4>
            <p class="card-description text-center" style="color:#ffffff;">Your password has been changed</p>
        </div>
        
        <p class="text-center"><a href="{% url 'login' %}" class="fgpass">Sign in Here!</a></p>
</div>
</div>
{% endblock %}

frontend/user/templates/user/password_reset_confirm.html
{% extends "topics/base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
		
<form id="reset_form" method="POST">
	{% csrf_token %}
	<div class="card card-login card-hidden">
		
		<div class="card-header card-header-primary text-center">
			<h4 class="card-title">Reset Password</h4>
				<p class="card-description text-center" style="color:#ffffff;">Set a new password</p>
						<div class="toooltip">Password Guidelines
						</div>				
		</div>
				
		<div class="card-body ">
				<span class="bmd-form-group">
					<div class="input-group">
						<div class="input-group-prepend">
						<span class="input-group-text">
						<i class="material-icons">lock_outline</i>
						</span>
						</div>
						{{ form.new_password1|add_class:"form-control"|append_attr:"placeholder:Password.."}}
					</div>
				</span>
		</div>

		<div class="card-body ">
				<span class="bmd-form-group">
					<div class="input-group">
						<div class="input-group-prepend">
						<span class="input-group-text">
						<i class="material-icons">lock_outline</i>
						</span>
						</div>
						{{ form.new_password2|add_class:"form-control"|append_attr:"placeholder:Confirm Password.."}}
					</div>
				</span>
		</div>		
				
		<div class="card-footer justify-content-center">
			<button class="btn btn-login btn-link btn-lg">Reset Password</button>
		</div>
			
		<p class="text-center"><a href="{% url 'login' %}" class="fgpass">Take me back!</a></p>

	</div>   
</form>
</div>	
{% endblock %}

frontend/user/templates/user/password_reset_done.html
{% extends "topics/base.html" %}
{% block content %}

<div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
<div class="card card-login card-hidden">
        <div class="card-header card-header-primary text-center">
            <h4 class="card-title">Email Sent</h4>
            <p class="card-description text-center" style="color:#ffffff;">An email has been sent with instructions to reset your password </p>
        </div>
        
        <p class="text-center"><a href="{% url 'login' %}" class="fgpass">Take me back!</a></p>
</div>
</div>
{% endblock %}